Repository cf-control/cf-control, pull requests merged in 2020-06, with the labels that each got.

#46 Remove Space Developer functionality implemented - Author: Alex Collaborator: Yen
  cloud.foundry.cli/build.gradle
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/exceptions/InvalidOperationException.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/util/FileUtils.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/operations/SpaceDevelopersOperations.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/BaseController.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/CreateController.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/GetController.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/UpdateController.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/operations/SpaceDevelopersOperationsTest.java
Labels: enhancement

#51 Refactoring the CLI
  .travis.yml
  cloud.foundry.cli/build.gradle
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/BaseController.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/CreateController.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/GetController.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/UpdateController.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/operations/ServicesOperationsTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/operations/SpaceDevelopersOperationsTest.java
Labels: enhancement

#47 Features/ref support
  README.md
  cloud.foundry.cli/build.gradle
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/exceptions/InvalidFileTypeException.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/exceptions/RefResolvingException.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/exceptions/YamlTreeNodeNotFoundException.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/FileUtils.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/RefResolver.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/YamlMapper.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/YamlPointer.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/YamlTreeDescender.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/YamlTreeVisitor.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/beans/SpecBean.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/beans/TargetBean.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/util/FileUtils.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/util/YamlCreator.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/BaseController.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/CreateController.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/GetController.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/UpdateController.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/YamlDemoTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/crosscutting/mapping/FileUtilsTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/crosscutting/mapping/RefResolverTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/crosscutting/mapping/YamlMapperTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/crosscutting/mapping/YamlPointerTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/crosscutting/mapping/YamlTreeDescenderTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/crosscutting/mapping/YamlTreeVisitorTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/crosscutting/util/FileUtilsTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/logic/GetLogicTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/operations/ApplicationsOperationsTest.java
  cloud.foundry.cli/src/test/resources/basic/Empty.yaml
  cloud.foundry.cli/src/test/resources/basic/NotYaml.yaml
  cloud.foundry.cli/src/test/resources/refresolver/Application.yml
  cloud.foundry.cli/src/test/resources/refresolver/ApplicationManifest.yml
  cloud.foundry.cli/src/test/resources/refresolver/ApplicationPath.yml
  cloud.foundry.cli/src/test/resources/refresolver/ApplicationPathWithRefProblem.yml
  cloud.foundry.cli/src/test/resources/refresolver/ApplicationWithRefProblem.yml
  cloud.foundry.cli/src/test/resources/refresolver/EscapeCharactersRef.yaml
  cloud.foundry.cli/src/test/resources/refresolver/ExpectedEscapeCharactersRef.yaml
  cloud.foundry.cli/src/test/resources/refresolver/ExpectedLocalRef.yaml
  cloud.foundry.cli/src/test/resources/refresolver/ExpectedRemoteRef.yaml
  cloud.foundry.cli/src/test/resources/refresolver/ExpectedUrlRef.yaml
  cloud.foundry.cli/src/test/resources/refresolver/InvalidPointerInRef.yaml
  cloud.foundry.cli/src/test/resources/refresolver/LocalRef.yaml
  cloud.foundry.cli/src/test/resources/refresolver/NonExistentFileRemoteRef.yaml
  cloud.foundry.cli/src/test/resources/refresolver/RemoteRef.yaml
  cloud.foundry.cli/src/test/resources/refresolver/TopLevelRef.yaml
  cloud.foundry.cli/src/test/resources/refresolver/UnreachableUrlRef.yaml
  cloud.foundry.cli/src/test/resources/refresolver/UrlRef.yaml
  cloud.foundry.cli/src/test/resources/refresolver/WronglyFormattedUrlRef.yaml
Labels: enhancement

#63 Fix Nullpointer and revert to usageinstead of default GetAll logic
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/GetController.java
Labels: bug

#62 Show Differences between services in Declaration and Live System impl…
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/DiffController.java
  cloud.foundry.cli/src/test/resources/demo/services.yml
Labels: backlog-item, enhancement

#75 Get rid of annoying Javers log messages
  cloud.foundry.cli/build.gradle
Labels: enhancement

#74 Feature/create apps dynamically
  README.md
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/exceptions/ApplyException.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/exceptions/DiffException.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/beans/ApplicationBean.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/beans/ApplicationManifestBean.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/beans/ConfigBean.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/beans/ServiceBean.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/beans/SpaceDevelopersBean.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/beans/SpecBean.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/ApplyLogic.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/DiffLogic.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/apply/ApplicationApplier.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/apply/CfChangeVisitor.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/diff/DiffNode.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/diff/DiffResult.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/diff/change/CfChange.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/diff/change/ChangeParser.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/diff/change/container/CfContainerChange.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/diff/change/map/CfMapChange.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/diff/change/object/CfNewObject.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/diff/change/object/CfObjectValueChanged.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/diff/change/object/CfRemovedObject.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/diff/output/DiffOutput.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/ApplyController.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/BaseController.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/logic/ApplyLogicTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/logic/DiffLogicTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/logic/apply/ApplicationApplierTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/logic/diff/DiffNodeTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/logic/diff/DiffResultTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/logic/diff/DifferTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/logic/diff/output/DiffOutputTest.java
Labels: backlog-item, enhancement

#73 Describe existing logging options in README
  README.md
Labels: backlog-item, bug

#80 Fix logging verbosity configuration bug
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/logging/Log.java
Labels: backlog-item

#79 Configure logging from CLI
  README.md
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/logging/Log.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/BaseController.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/crosscutting/logging/LogTest.java
Labels: backlog-item, enhancement

#82 Fix exception when no logging option is specified
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/BaseController.java
Labels: bug

#87 Improve service deletion
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/UpdateController.java
Labels: backlog-item, enhancement

#96 Enforce default console log format
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/logging/Log.java
Labels: backlog-item, enhancement

#94 Log factory pattern
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/logging/Log.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/CfOperationsCreator.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/RefResolver.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/ApplyLogic.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/GetLogic.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/apply/ApplicationApplier.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/diff/change/ChangeParser.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/operations/ApplicationsOperations.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/operations/ServicesOperations.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/operations/SpaceDevelopersOperations.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/ApplyController.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/BaseController.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/CreateController.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/DiffController.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/GetController.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/UpdateController.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/crosscutting/logging/LogTest.java
Labels: backlog-item, refactoring

#95 Add --log-file CLI flag
  README.md
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/BaseController.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/crosscutting/logging/LogFileTest.java
Labels: backlog-item, enhancement
