Repository cf-control/cf-control, pull requests merged in 2020-07, with the labels that each got.

#104 remove applications
  README.md
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/ApplyLogic.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/apply/ApplicationRequestsPlaner.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/diff/Differ.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/operations/ApplicationsOperations.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/ApplyController.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/logic/ApplyLogicTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/logic/apply/ApplicationRequestPlanerTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/logic/diff/DifferTest.java
Labels: backlog-item, enhancement

#114 Feature/dump command
  README.md
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/CfArgumentsCreator.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/YamlMapper.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/beans/ApplicationBean.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/BaseController.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/DumpController.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/crosscutting/mapping/CfArgumentsCreatorTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/crosscutting/mapping/YamlMapperTest.java
  cloud.foundry.cli/src/test/resources/refresolver/ApplicationPathWithInterpretationProblem.yml
  cloud.foundry.cli/src/test/resources/refresolver/ApplicationPathWithSyntaxProblem.yml
Labels: backlog-item, enhancement

#118 Feature/apply state app tags
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/FileUtils.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/beans/ApplicationBean.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/beans/ApplicationManifestBean.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/apply/ApplicationRequestsPlaner.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/apply/RequestsPlaner.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/diff/Differ.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/diff/change/CfChange.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/diff/change/ChangeParser.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/diff/change/parsing/AbstractParsingStrategy.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/diff/change/parsing/ContainerChangeParsingStrategy.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/diff/change/parsing/MapChangeParsingStrategy.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/diff/change/parsing/NewObjectParsingStrategy.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/diff/change/parsing/ParsingStrategy.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/diff/change/parsing/RemovedObjectParsingStrategy.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/diff/change/parsing/ValueChangeParsingStrategy.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/operations/ApplicationsOperations.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/crosscutting/mapping/FileUtilsTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/logic/ApplyLogicTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/logic/GetLogicTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/logic/apply/ApplicationRequestPlanerTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/logic/diff/DifferTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/logic/diff/change/ChangeParserTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/logic/diff/parsing/ContainerChangeParsingStrategyTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/logic/diff/parsing/MapChangeParsingStrategyTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/logic/diff/parsing/NewObjectParsingStrategyTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/logic/diff/parsing/RemovedObjectParsingStrategyTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/logic/diff/parsing/ValueChangeParsingStrategyTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/mocking/ApplicationsMockBuilder.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/mocking/ApplicationsV3MockBuilder.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/mocking/CloudFoundryClientMockBuilder.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/mocking/DefaultCloudFoundryOperationsMockBuilder.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/operations/ApplicationsOperationsTest.java
Labels: backlog-item, enhancement

#122 Resolve $ref entries relative to their parent file's directory
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/FileUtils.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/RefResolver.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/YamlMapper.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/crosscutting/mapping/FileUtilsTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/crosscutting/mapping/RefResolverTest.java
  cloud.foundry.cli/src/test/resources/demo/refDemo.yml
  cloud.foundry.cli/src/test/resources/refresolver/Application.yml
  cloud.foundry.cli/src/test/resources/refresolver/ApplicationWithRefProblem.yml
  cloud.foundry.cli/src/test/resources/refresolver/EscapeCharactersRef.yaml
  cloud.foundry.cli/src/test/resources/refresolver/InvalidPointerInRef.yaml
  cloud.foundry.cli/src/test/resources/refresolver/RemoteRef.yaml
  cloud.foundry.cli/src/test/resources/refresolver/TopLevelRef.yaml
Labels: backlog-item, enhancement

#109 System tests: infrastructure and first tests for get command
  .travis.yml
  cloud.foundry.cli/build.gradle
  cloud.foundry.cli/gradle/wrapper/gradle-wrapper.properties
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/CfOperationsCreator.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/RefResolver.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/YamlMapper.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/ApplyController.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/CreateController.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/DiffController.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/LoginCommandOptions.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/UpdateController.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/crosscutting/logging/LogFileTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/crosscutting/mapping/YamlMapperTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/logic/diff/DifferTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/system/GetAllCommandTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/system/LogFileTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/system/StandardErrCapturingTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/system/SystemTestBase.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/system/util/ArgumentsBuilder.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/system/util/PreventExitSecurityManager.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/system/util/RunResult.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/system/util/SpaceManager.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/system/util/StreamContents.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/system/util/StreamManager.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/system/util/SystemExitException.java
Labels: backlog-item, enhancement, refactoring

#133 Fix tests on windows
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/FileUtils.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/RefResolver.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/crosscutting/mapping/FileUtilsTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/crosscutting/mapping/RefResolverTest.java
Labels: bug

#132 Don't append login options for base controller
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/CfArgumentsCreator.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/crosscutting/mapping/CfArgumentsCreatorTest.java
Labels: bug

#130 use params from yaml for diff/apply commands
  README.md
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/CfArgumentsCreator.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/crosscutting/mapping/CfArgumentsCreatorTest.java
  cloud.foundry.cli/src/test/resources/basic/configBean.yml
Labels: backlog-item, enhancement

#125 Apply State: App Manifest
  README.md
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/beans/ApplicationBean.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/beans/ApplicationManifestBean.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/validation/ObjectPropertyValidation.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/ApplyLogic.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/DiffLogic.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/apply/ApplicationRequestsPlaner.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/diff/DiffResult.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/operations/ApplicationsOperations.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/operations/RouteUtils.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/operations/ServicesOperations.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/ApplyController.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/crosscutting/mapping/validation/ObjectPropertyValidationTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/logic/ApplyLogicTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/logic/apply/ApplicationRequestPlanerTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/mocking/ApplicationsMockBuilder.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/mocking/ApplicationsV3MockBuilder.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/mocking/DefaultCloudFoundryOperationsMockBuilder.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/operations/ApplicationsOperationsTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/operations/ServicesOperationsTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/system/GetAllCommandTest.java
Labels: enhancement

#143 Better log messages
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/CfArgumentsCreator.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/CfOperationsCreator.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/RefResolver.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/ApplyLogic.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/GetLogic.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/apply/ApplicationRequestsPlanner.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/apply/RequestsPlanner.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/apply/ServiceRequestsPlanner.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/apply/SpaceDevelopersRequestsPlanner.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/diff/change/ChangeParser.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/logic/diff/change/parsing/ContainerChangeParsingStrategy.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/operations/ApplicationsOperations.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/operations/ServicesOperations.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/operations/SpaceDevelopersOperations.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/operations/SpaceOperations.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/ApplyController.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/BaseController.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/DiffController.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/DumpController.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/GetController.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/RenameController.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/logic/apply/ApplicationRequestPlannerTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/logic/apply/ServicesRequestsPlannerTest.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/logic/apply/SpaceDevelopersRequestsPlannerTest.java
Labels: backlog-item, enhancement

#153 Make sure parent path can be calculated by cf-control
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/RefResolver.java
Labels: bug

#145 Improve error messages when loading yaml files
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/exceptions/YamlParsingException.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/RefResolver.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/YamlMapper.java
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/services/BaseController.java
  cloud.foundry.cli/src/test/java/cloud/foundry/cli/crosscutting/mapping/YamlMapperTest.java
  cloud.foundry.cli/src/test/resources/refresolver/ApplicationWithRefProblem.yml
  cloud.foundry.cli/src/test/resources/refresolver/YamlInterpretationProblem.yml
  cloud.foundry.cli/src/test/resources/refresolver/YamlSyntaxProblem.yml
Labels: backlog-item, enhancement

#158 Fix bug where target information is unintentionally manipulated
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/crosscutting/mapping/CfOperationsCreator.java
Labels: bug

#161 Avoid errors in apply while removing service
  cloud.foundry.cli/src/main/java/cloud/foundry/cli/operations/ApplicationsOperations.java
Labels: bug
